### PR TITLE
Better dpad input handling.

### PR DESCRIPTION
**Pull request by avahe-kellenberger**
The current way inputs are handled is terrible. This makes it less terrible.

I don't really like my implementation, but the `ninput` library sucks, this was the only way I could get it to work.

Now, 1 input = 1 change to the UI.

---

Unrelated side-note (there's no issue tracker), this mod doesn't work with the training modpack (the training modpack will crash). 
image

If you have any idea of how to fix it, that would be nice. Atm I'm using my own version of the latency mod which has the same functionality as yours, but does not modify text on the CSS (so it can be used in conjunction with the training mod pack).

### CODE REVIEW

**Comment by avahe-kellenberger** [comment]
With my PR it can't be held, but having 1-to-1 input responsiveness helps consistency when changing values when in "stealth mode" which I think is valuable. If you'd like to accept these changes, I'll go ahead and update the PR to use a struct like you mentioned.

Thanks for the update!

**Comment by xNaxdy** [comment]
That's a good point actually, then yeah it would make sense to have it be 1 input = 1 change. With a struct I'd be happy to merge it.

**Comment by avahe-kellenberger** [comment]
I'm not very familiar with Rust, this works but feel free to clean it up as you wish

**Comment by avahe-kellenberger** [comment]
Side note, I've been having ARCropolis crash on me a lot in arenas, now that I've added this mod. Have you seen this issue yourself?
arcropolis_crash

**Comment by xNaxdy** [comment]
Could it be this? https://github.com/xNaxdy/latency-slider-de/issues/18

If not, I suggest opening a separate issue (they're enabled again now)

**Pull request merged**
